metro = float(input('Informe a distância em metro: '))
cen = int(metro * 100)
print(f'A distância em metros {metro} convertido para centimetros é: {cen}')
mili = int(cen * 1000)
print(f'E convertendo centimetros {cen} para milimetro, o resultado vai ser: {mili}')