coisa = input('Escreva algo: ')
print(type(coisa))
print(coisa, 'É alpha?')
print(coisa.isalpha())
print(coisa, 'É númerico?')
print(coisa.isnumeric())
print(coisa, 'É alphanumérico?')
print(coisa.isalnum())
print(coisa, 'Letra maiúscula?')
print(coisa.isupper())
print(coisa, 'Letra minúsculo')
print(coisa.islower())
print(coisa, 'É asci?')
print(coisa.isascii())
print(coisa, 'Tem espaços?')
print(coisa.isspace())