print('Olá, queremos saber mais de você.')
data = input('Nos informe qual sua data de nascimento:')
mes = input('Qual o mês de nascimento?')
ano = input('E o ano?')
print('Está é sua data de nascimento:',data, 'do mês',mes, 'de',ano)